class Bar:
    def __init__(self):
        self.menu = {"popcorn": 5, "soda": 3}

    def sell(self, item_name: str, customer) -> bool:
        price = self.menu.get(item_name)
        if price is None:
            raise ValueError(f"No such item: {item_name}")
        if customer.money >= price:
            customer.money -= price
            customer.snacks.append(item_name)
            return True
        return False


